import React from 'react'

const About = () => {
  return (
    <>

      <title>WeatherX - Your weather assistant</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />





      <div>

        <section className="text-gray-600 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
              <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Welcome to WeatherX
                <br className="hidden lg:inline-block" />- "your ultimate weather companion!"
              </h1>
              <p className="mb-8 leading-relaxed">" Our app provides you with accurate and up-to-date weather information for any location in the world. With a sleek and user-friendly interface, you can easily check the current temperature, humidity, wind speed, and more. Our advanced forecasting system allows you to plan your day ahead with confidence, and our real-time alerts ensure that you're always prepared for any weather changes. Download Weatherx today and stay ahead of the weather!"</p>
              <div className="flex justify-center">
                <button className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"><a href="/Weather">Weather</a></button>
                <button className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"><a href="/Contact">ContactUs</a></button>


              </div>
            </div>
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
              <img className="object-cover object-center rounded" alt="hero" src="https://cdn.wallpapersafari.com/5/84/Y4HSCf.jpg" />
            </div>
          </div>
        </section>

      </div>
    </>
  )
}

export default About
