import React, { useState, useEffect } from 'react'


const Weather = () => {

  const [query, setQuery] = useState("")
  const [delhi, setDelhi] = useState()
  const [nyc, setNyc] = useState()
  const [london, setLondon] = useState()
  const [tokyo, setTokyo] = useState()
  const [shanghai, setShanghai] = useState()
  const [dhaka, setDhaka] = useState()
  const [mexico, setMexico] = useState()
  const [mumbai, setMumbai] = useState()
  const [cairo, setCairo] = useState()
  const [weather, setWeather] = useState()

  const fetchWeather = async (query) => {
    let weather = await fetch("https://api.weatherapi.com/v1/current.json?key=959e132e2ca84be2a21145747232904&q=" + query)
    let response = await weather.json()
    if (Object.keys(response).includes("error")) {

      // the weather is undefined

    }
    console.log(response)
    return response
  }

  useEffect(() => {
    async function fetchData() {
      let delhi = await fetchWeather("New Delhi")
      setDelhi(delhi)


      let nyc = await fetchWeather("New York")
      setNyc(nyc)


      let london = await fetchWeather("London")
      setLondon(london)


      let tokyo = await fetchWeather("Tokyo")
      setTokyo(tokyo)


      let shanghai = await fetchWeather("Shanghai")
      setShanghai(shanghai)


      let dhaka = await fetchWeather("Dhaka")
      setDhaka(dhaka)


      let mexico = await fetchWeather("Mexico")
      setMexico(mexico)

      let mumbai = await fetchWeather("Mumbai")
      setMumbai(mumbai)


      let cairo = await fetchWeather("Cairo")
      setCairo(cairo)

    }
    fetchData();





  }, [])

  const handleChange = (e) => {
    setQuery(e.target.value)
    if (e.target.value.length <= 0) {
      setWeather(undefined)
    }
  }
  const handleClick = async (e) => {

    let w = await fetchWeather(query)
    setWeather(w)

  }



  return (

    <>

      <title>WeatherX - Your weather assistant</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />


      <div className='container mx-auto'>
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-col">
              <div className="h-1 bg-gray-200 rounded overflow-hidden">
                <div className="w-24 h-full bg-indigo-500"></div>
              </div>
              <div className="flex flex-wrap sm:flex-row flex-col py-6 mb-2">
                <h1 className="sm:w-2/5 text-gray-900 font-medium title-font text-2xl mb-2 sm:mb-0">WeatherX</h1>
                <div className="sm:w-3/5 leading-relaxed text-base sm:pl-10 pl-0">Search for a Location and we will fetch the weather for you</div>
                <input value={query} onChange={handleChange} className='w-full  rounded-md border-purple-400 py-1 border-2 m-2' type="text" name="search" id="search" />
                <button onClick={handleClick} className="flex mx-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Search Weather</button>
              </div>
              {(weather && query.length > 0) && <div className='mb-4'>The weather of {query} is {weather && weather.current.temp_c} &#8451; and the windspeed is {weather.current.wind_mph} mph </div>}
            </div>
            <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://www.hdwallpaper.nu/wp-content/uploads/2015/04/546389.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">London<span className="text-gray-600">(England)</span></h2>
                <div className="text-base leading-relaxed mt-2">{london && <div>The weather in London is {london.current.temp_c}&#8451; and the windspeed is {london.current.wind_mph} mph</div>}</div>

              </div>
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://wallpapercave.com/wp/wp3917608.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">New Delhi<span className="text-gray-600">(India)</span></h2>
                <div className="text-base leading-relaxed mt-2">{delhi && <div>The weather in Delhi is {delhi.current.temp_c}&#8451; and the windspeed is {delhi.current.wind_mph} mph</div>}</div>

              </div>
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="http://oedb.org/wp-content/uploads/new-york.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">New York<span className="text-gray-600">(United States)</span></h2>
                <div className="text-base leading-relaxed mt-2">{nyc && <div>The weather in NYC is {nyc.current.temp_c}&#8451; and the windspeed is {nyc.current.wind_mph} mph</div>}</div>

              </div>
            </div>



            <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://sojournermoxie.com/wp-content/uploads/2019/08/ShinjukuTokyo.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">Tokyo<span className="text-gray-600">(Japan)</span></h2>
                <div className="text-base leading-relaxed mt-2">{tokyo && <div>The weather in Tokyo is {tokyo.current.temp_c}&#8451; and the windspeed is {tokyo.current.wind_mph} mph</div>}</div>

              </div>
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://cdn.britannica.com/15/177615-050-5587429C/Pavilion-Yuyuan-Garden-Shanghai-China.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">Shanghai<span className="text-gray-600">(China)</span></h2>
                <div className="text-base leading-relaxed mt-2">{shanghai && <div>The weather in Shanghai is {shanghai.current.temp_c}&#8451; and the windspeed is {shanghai.current.wind_mph} mph</div>}</div>

              </div>
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://farm4.staticflickr.com/3871/14696333789_181ea6dae7_b.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">Dhaka<span className="text-gray-600">(Bangladesh)</span></h2>
                <div className="text-base leading-relaxed mt-2">{dhaka && <div>The weather in Dhaka is {dhaka.current.temp_c}&#8451; and the windspeed is {dhaka.current.wind_mph} mph</div>}</div>

              </div>


            </div>




            <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4">
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://www.fodors.com/wp-content/uploads/2019/03/HERO_MexicoCityMisconceptions_Hero_shutterstock_573127864.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">Mexico City<span className="text-gray-600">(Mexico)</span></h2>
                <div className="text-base leading-relaxed mt-2">{mexico && <div>The weather in Mexico City is {mexico.current.temp_c}&#8451; and the windspeed is {mexico.current.wind_mph} mph</div>}</div>

              </div>
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://img.cdn.zostel.com/blog_photo/MUMBAI_BLOG_COVER.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">Mumbai<span className="text-gray-600">(India)</span></h2>
                <div className="text-base leading-relaxed mt-2">{mumbai && <div>The weather in Mumbai is {mumbai.current.temp_c}&#8451; and the windspeed is {mumbai.current.wind_mph} mph</div>}</div>

              </div>
              <div className="p-4 md:w-1/3 sm:mb-0 mb-6">
                <div className="rounded-lg h-64 overflow-hidden">
                  <img alt="content" className="object-cover object-center h-full w-full" src="https://farm4.staticflickr.com/3871/14696333789_181ea6dae7_b.jpg" />
                </div>
                <h2 className="text-xl font-medium title-font text-gray-900 mt-5">Cairo<span className="text-gray-600">(Egypt)</span></h2>
                <div className="text-base leading-relaxed mt-2">{cairo && <div>The weather in Cairo is {cairo.current.temp_c}&#8451; and the windspeed is {cairo.current.wind_mph} mph</div>}</div>

              </div>


            </div>








          </div>
        </section>
      </div>

    </>
  )
}

export default Weather


// ({london.current.temp_c} &#8451;)